name: $name
version: $version
main: me.milesglitch.statusplugin.StatusPlugin
description: $description
website: "https://github.com/0xAX88M2/StatusPlugin"
authors:
  - MilesGlitch
api-version: "$apiVersion"